import React from 'react';
import Head from 'next/head';


export const Heading = ({ title }: {title:string}) => (
  <Head>
    <title>{title}</title>
    <meta name="description" content="Generated by create next app" />
    <link rel="icon" href="/favicon.ico" />
  </Head>
)
 